// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6EyGt3O12Smvw_KcmHCPDhC5uqu-ZDA',
    appId: '1:229104362816:web:afa4d3aceb620763e906a5',
    messagingSenderId: '229104362816',
    projectId: 'msp-mobile-app-project',
    authDomain: 'msp-mobile-app-project.firebaseapp.com',
    storageBucket: 'msp-mobile-app-project.appspot.com',
    measurementId: 'G-8JSK86MECT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUF0bgy4iX1vz0v_SfqJHgPGrwGO46xY',
    appId: '1:229104362816:android:dc58b79a3098132be906a5',
    messagingSenderId: '229104362816',
    projectId: 'msp-mobile-app-project',
    storageBucket: 'msp-mobile-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVRepvSOC_6ROvkiJQgVG0Se7l_VrXlGg',
    appId: '1:229104362816:ios:ecf6b185758b1a23e906a5',
    messagingSenderId: '229104362816',
    projectId: 'msp-mobile-app-project',
    storageBucket: 'msp-mobile-app-project.appspot.com',
    iosBundleId: 'com.example.bestMspTeam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVRepvSOC_6ROvkiJQgVG0Se7l_VrXlGg',
    appId: '1:229104362816:ios:59137fe396a51ae1e906a5',
    messagingSenderId: '229104362816',
    projectId: 'msp-mobile-app-project',
    storageBucket: 'msp-mobile-app-project.appspot.com',
    iosBundleId: 'com.example.bestMspTeam.RunnerTests',
  );
}
